# 
# To create the conda environment:
# $ conda env create -f environment.yml
# 
# To update the conda environment:
# $ conda env update -f environment.yml
# 
# To register the conda environment in Jupyter:
# $ conda activate cv
# $ python -m ipykernel install --user --name cv
# 
name: cv
channels:
- defaults
- conda-forge
- pytorch
- fastai
dependencies:
- python==3.6.8
- pytorch>=1.2.0
- torchvision>=0.3.0
- pycocotools>=2.0
- fastai==1.0.57
- ipykernel>=4.6.1
- jupyter>=1.0.0
- pytest>=3.6.4
- bqplot
- scikit-learn>=0.19.1
- pip>=19.0.3
- cython>=0.29.1
- pip:
  - azureml-sdk[notebooks,contrib]>=1.0.30
  - black>=18.6b4
  - papermill>=0.15.0
  - ipywebrtc
  - nvidia-ml-py3
  - pre-commit>=1.14.4
  - nteract-scrapbook
  # - git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI
  - pyyaml>=5.1.2
  - scrapbook>=0.2.0
  - lxml>=4.3.2
  - requests>=2.22.0
