# 
# To create the conda environment:
# $ conda env create -f environment.yml
# 
# To update the conda environment:
# $ conda env update -f environment.yml
# 
# To register the conda environment in Jupyter:
# $ conda activate cvbp
# $ python -m ipykernel install --user --name cvbp
# 
name: cvbp
channels:
- defaults
- conda-forge
- pytorch
- fastai
dependencies:
- python==3.6.8
- pytorch==1.0.0
- torchvision  
- fastai==1.0.48
- ipykernel>=4.6.1
- jupyter>=1.0.0
- pytest>=3.6.4
- bqplot
- scikit-learn>=0.19.1
- pip:
  - azureml-sdk[notebooks,contrib]>=1.0.30
  - black>=18.6b4
  - papermill>=0.15.0
  - ipywebrtc
  - pre-commit>=1.14.4
  - lxml>=4.3.2
  - pyyaml>=5.1 
  - nteract-scrapbook
