# This file is almost similar to azure-pipelines-gpu.yml file, key difference is
# we are running our builds only on Linux machine.  
# Pull request against these pipelines will trigger this build
pr:
- master
- staging

#Any commit to this branch will trigger the build.
trigger:
- staging
- master

pool:
  name: cvbpbuildagents
  vmImage: 'linuxagent-gpu'

steps:

- bash: |
    echo "##vso[task.prependpath]/data/anaconda/bin"
  displayName: Add Conda to PATH

- bash: |
    source deactivate cvbp
    conda remove -q -n cvbp --all -y
    conda env create -f image_classification/environment.yml
    conda env list  
    source activate cvbp
  displayName: 'Build Configuration'

- bash: |
    cd image_classification
    source activate cvbp
    python -m ipykernel install --user --name cvbp --display-name "cvbp"
    pytest tests/unit --junitxml=junit/test-unitttest.xml
  displayName: 'Run Unit tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-unitttest.xml'
    testRunTitle: 'Test results for PyTest'

