# 
# To create the conda environment:
# $ conda env create -f environment.yaml
# 
# To update the conda environment:
# $ conda env update -f environment.yaml
# 
# To register the conda environment in Jupyter:
# $ conda activate cvbp
# $ python -m ipykernel install --user --name cvbp
# 
name: cvbp
channels:
- defaults
- conda-forge
- pytorch
- fastai
dependencies:
- fastai>=1.0.42
- fastparquet>=0.1.6
- gitpython>=2.1.8
- ipykernel>=4.6.1
- jupyter>=1.0.0
- matplotlib>=2.2.2
- numpy>=1.13.3
- pandas>=0.23.4
- python==3.6.8
- pytest>=3.6.4
- pytorch==1.0.0
- seaborn>=0.8.1
- scipy>=1.0.0
- tensorflow-gpu==1.12.0
- numba>=0.38.1
- pip:
  - azureml-sdk[notebooks,contrib]==1.0.10
  - azure-storage>=0.36.0
  - black>=18.6b4
  - torchvision
  - memory-profiler>=0.54.0
  - nvidia-ml-py3>=7.352.0
  - papermill>=0.15.0
  - pillow
  - ipywebrtc
  - pytest
