name: cvbp
channels:
  - conda-forge
  - defaults
dependencies:
  - nb_conda=2.2.1
  - nb_conda_kernels=2.1.1
  - nbconvert=5.3.1
  - pip=10.0.1
  - python=3.6.7
  - prompt_toolkit=1.0.15
  - pip:
    - azure==4.0.0
    - azure.mgmt.common==0.20.0
    - azure-cli==2.0.55
    - torch==0.4.1
    - torchvision==0.2.1
    - fastai==1.0.42

